FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    nsis \
    nsis-pluginapi \
    wine \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY . .

CMD ["makensis", "/DVERSION=1.0.0", "servin-installer.nsi"]
