version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Buildfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - API_URL=http://api:3000
    volumes:
      - ./public:/app/public
      - web_data:/app/data
    networks:
      - app_network
    depends_on:
      - api
      - db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"

  api:
    image: node:16-alpine
    command: ["npm", "start"]
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: myapp
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - ./api:/app
      - api_logs:/app/logs
    networks:
      - app_network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - web_data:/usr/share/nginx/html
    networks:
      - app_network
    depends_on:
      - web
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    labels:
      - "com.example.description=Database data volume"
  redis_data:
    driver: local
  web_data:
    driver: local
  api_logs:
    driver: local

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    labels:
      - "com.example.description=Application network"
